import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "./components/Navbar";
import { Footer } from "./components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-kanit">
        <Navbar mainNavigation={Navigation} />
        {children}
        <Footer />
      </body>
    </html>
  );
}

export const Navigation = [
  {
    title: "Home",
    url: "/",
  },
  {
    title: "About Us",
    url: "/",
  },
  {
    title: "Services",
    url: "/",
    children: [
      {
        title: "Product Design",
        url: "/service",
        list: ["UI/UX Designer", "Web Design", "Branding", "Landing Page"],
        iconPath: "/icons/navigation/pen.svg",
      },
      {
        title: "Product Development",
        url: "/service",
        list: [
          "Web development",
          "Software development",
          "CMS development",
          "No-code development",
        ],
        iconPath: "/icons/navigation/laptop-code.svg",
      },
      {
        title: "Product Growth & Care",
        url: "/service",
        list: [
          "Content marketing",
          "Digital Marketing",
          "Pitch deck design",
          "SEO",
        ],
        iconPath: "/icons/navigation/graphic-up.svg",
      },
    ],
  },
  {
    title: "Portofolio",
    url: "/portofolio",
  },
  {
    title: "Career",
    url: "/career",
  },
  {
    title: "Blog",
    url: "/",
  },
];
